server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetchRegistry : true  
  
secret-key: secret
COOKIE: authenticate
       

internal.authentication.secret-key : STACKQUOTIENT-INTERNAL-DEV-SECRET-KEY
partners.authentication.secret-key : STACKQUOTIENT-PARTNERS-DEV-SECRET-KEY


# gateway.security.excluded.routes: /, /*.ico, /*.js, /assets/*.jpeg,
#           /assets/*.png,/assets/*.svg, /*.jpg, /*.css,/*.woff2, /*.woff,
#           /usermanagementservice/api/v1/login/**,
#           /usermanagementservice/api/v1/oauth/**,
#           /usermanagementservice-cts/api/v1/login/**,
#           /usermanagementservice-cts/api/v1/oauth/**,
#           /codingquizplayengine/api/v1/quizplay/codingengine/evalResults,
#           /calibrations/**,
#           /usermanagementservice/calibrations/**,
#           /usermanagementservice/api/v1/login/otp/**,
#           /usermanagementservice/resend/**


#  gateway.security.partners.routes: /usermanagementservice/api/v1/partners/**

#  gateway.security.internal.routes: /codingquizplayengine/api/v1/internal/**, 
#                                    /quizinventory/api/v1/internal/**, 
#                                    /usermanagementservice/api/v1/internal/** 

spring:
  cloud:
    gateway:
      routes:
      - id: usermanagement
        uri: lb://usermanagementservice
        predicates:
          - Path=/usermanagementservice/**
        filters:
          - RewritePath=/usermanagementservice(?<segment>/?.*), $\{segment}

      - id: quizinventory
        uri: lb://quizinventory
        predicates:
          - Path=/quizinventory/**
        filters:
          - RewritePath=/quizinventory(?<segment>/?.*), $\{segment}

      - id: questioninventory
        uri: lb://questioninventory
        predicates:
          - Path=/questioninventory/**
        filters:
          - RewritePath=/questioninventory(?<segment>/?.*), $\{segment}

      - id: quizplay
        uri: lb://quizplayservice
        predicates:
          - Path=/quizplayservice/**
        filters:
          - RewritePath=/quizplayservice(?<segment>/?.*), $\{segment}

      - id: resourcesservice
        uri: lb://resourcesservice
        predicates:
          - Path=/resourcesservice/**
        filters:
          - RewritePath=/resourcesservice(?<segment>/?.*), $\{segment}
     
      - id: semanticservice
        uri: lb://semanticservice
        predicates:
          - Path=/semanticservice/**
        filters:
          - RewritePath=/semanticservice(?<segment>/?.*), $\{segment}  
      
      - id: codingquizplay
        uri: lb://codingquizplayengine
        predicates:
          - Path=/codingquizplayengine/**
        filters:
          - RewritePath=/codingquizplayengine(?<segment>/?.*), $\{segment} 

      - id: usermanagementservice-cts
        uri: lb://usermanagementservice-cts
        predicates:
          - Path=/usermanagementservice-cts/**
        filters:
          - RewritePath=/usermanagementservice-cts(?<segment>/?.*), $\{segment} 

      - id: quizplay-cts
        uri: lb://quizplayservice-cts
        predicates:
          - Path=/quizplayservice-cts/**
        filters:
          - RewritePath=/quizplayservice-cts(?<segment>/?.*), $\{segment}
      
      - id: codingquizplay-cts
        uri: lb://codingquizplayengine-cts
        predicates:
          - Path=/codingquizplayengine-cts/**
        filters:
          - RewritePath=/codingquizplayengine-cts(?<segment>/?.*), $\{segment}  
    
      - id: usermanagementservice-ibm
        uri: lb://usermanagementservice-ibm
        predicates:
          - Path=/usermanagementservice-ibm/**
        filters:
          - RewritePath=/usermanagementservice-ibm(?<segment>/?.*), $\{segment} 

      - id: quizplay-ibm
        uri: lb://quizplayservice-ibm
        predicates:
          - Path=/quizplayservice-ibm/**
        filters:
          - RewritePath=/quizplayservice-ibm(?<segment>/?.*), $\{segment}
      
      - id: codingquizplay-ibm
        uri: lb://codingquizplayengine-ibm
        predicates:
          - Path=/codingquizplayengine-ibm/**
        filters:
          - RewritePath=/codingquizplayengine-ibm(?<segment>/?.*), $\{segment}         

      - id: webapplication
        uri: lb://webapplication
        predicates:
          - Path=/**
        filters:
          - RewritePath=(?<segment>/?.*), $\{segment}    

      
     
      

      # - id: usermanagementservice 
      #   uri: lb://usermanagementservice 
      #   predicates:
       #   - Path=/calibrations/**  
        # filters:
        #   - StripPrefix=1
          #- RewritePath=/(?<segment>/?.*), $\{segment}
        
          

    
          
          
          
          
          
